//We can use multiple catch blocks to print error specific messages 
//the catch block which has error would be excecuted rest other catch blocks would be ignored


public class ExceptionDemo 
{
	public static void main(String[] args)
	{
		try
		{
			int a[] = new int[5];
			a[4] = 8;
			int i = 7;
			int j = 0;
			int k=i/j;
			System.out.println("output is " + k);
			System.out.println("Bye");
		}
		catch(ArithmeticException)
		{
			System.out.println("Error");
		}
		catch(ArrayIndexOutOfBoundsException e)
		{
			System.out.println("Out of bound error")
		}
		
	}
}
