we can also use the exception catch block that can handle any type of errors , make sure if you are using multiple catch blocks and you want to print multiple errors to rectify them
then declare exception catch block in the end . 


public class ExceptionDemo 
{
	public static void main(String[] args)
	{
		try
		{
			int a[] = new int[5];
			a[4] = 8;
			int i = 7;
			int j = 0;
			int k=i/j;
			System.out.println("output is " + k);
			System.out.println("Bye");
		}
		catch(ArithmeticException)
		{
			System.out.println("Error");
		}
		catch(ArrayIndexOutOfBoundsException e)
		{
			System.out.println("Out of bound error")
		}
		catch(Exception e)
		{
			System.out.println("Something wrong..");
		}
		
	}
}
